import Head from "next/head";
import { InstantSearch, Hits, SearchBox } from "react-instantsearch-hooks-web";
import { instantMeiliSearch } from "@meilisearch/instant-meilisearch";

export default function Home() {
  const searchClient = instantMeiliSearch("http://localhost:7700", "", {
    primaryKey: "Id",
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Search</h1>
        <InstantSearch indexName="movies" searchClient={searchClient}>
          <SearchBox />
          <Hits hitComponent={Hit} />
        </InstantSearch>
      </div>
    </>
  );
}

const Hit = ({ hit }) => {
  return (
    <div>
      <p>{hit.Title}</p>
    </div>
  );
};
